### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by vitalii2011**

### CODE REVIEW

**Comment by jtsage** [comment]
No doubt a new version will happen again this weekend, if not before, thanks for this.  I have noticed the machine translation is pretty terrible at Russian and Polish, some of the others it's not *that* bad.

**Comment by vitalii2011** [comment]
> No doubt a new version will happen again this weekend, if not before, thanks for this. I have noticed the machine translation is pretty terrible at Russian and Polish, some of the others it's not _that_ bad.

I don’t know about Polish, but since the beginning of 2021, translation into Russian has been offered in some kind of “childish” version, up to inventing non-existent words. But only if you didn't access Google Translate from Chrome. There was an opinion that this is how Google tried to "drag" users to its browser. Quite a dubious assumption, in my opinion. What really happened, I don't know. Now the translation is more or less adequate (into Russian), but out of habit, since then, I have been checking the translation on Yandex Translator.

**Comment by vitalii2011** [comment]
> …

Try, for translation files, Crowdin:
https://github.com/CitiesSkylinesMods/TMPE/wiki/Localization
One of the mod authors whose mods I did translations for:
https://crowdin.com/profile/algernon
Just to show what the modder will have on the site.
As a translator, it is convenient for me that when new, untranslated lines appear, a letter from the site comes about this:
Screenshot 2022-11-05 at 04-55-36 Почта Mail ru

**Comment by jtsage** [comment]
Yeah, I have the 'FS Mod Folder Checker' and another of my projects on there, I was trying to get the interface somewhat settled for 1.0.0 before I opened a project there and had to update it every few days.  Hopefully today or tomorrow I'll add a link for that :)

**Comment by jtsage** [comment]
https://crowdin.com/project/fsg-mod-assistant

Assuming I can figure out how, I'll tag you as a proofreader for the RU translation as well :)

**Comment by vitalii2011** [comment]
> …

- Added translation for one line. )
- It may be unnecessary to show in FSModAssistant, but in modDesc.xml it is sometimes required:
Image 001
- For FSModAssistant, this is not really necessary - open the program for a short time and look, but for translating the mod for the game it makes life very easy for the translator if there is a picture with the text location on Crowdin - you don’t need to open the game to understand whether the translation will fit in the interface, etc.:
Image 003
https://crowdin.com/translate/yet-another-toolbar/3/en-ru?filter=basic&value=0

**Comment by jtsage** [comment]
Yep, on my list of things to do - I'll dump screenshots of the whole program with highlights as to where these strings are.  I think I have it set to just use the string key if no translations are found, so that might be simpler in some ways - maybe a side by side with the key name and the original translation value.  But, that will take a bit of time to prepare.

Fwiw, the one you pointed out is a badge on the save game comparison screen, used when a mod is not found on the in game modhub (really useful for setting up multiplayer servers to make sure you can download everything from modhub if that is your goal)

**Comment by vitalii2011** [comment]
Thanks for the clarification. Added translation.

**Comment by jtsage** [comment]
I do get semi-regular updates from crowdin.  It doesn't send instantly, but it'll do a summary once a day or so to remind me to port them back in.  Thank you :)

**Pull request merged**
